### PR TITLE
Fix some `no_std` nits

### PR DESCRIPTION
**Pull request by pinkforest**
Noticed this - separate PR
- #2 

You'll need std for it's `Error` - however it's being brought to core but that requires high MSRV 1.80

### CODE REVIEW

**Comment by rozbb** [comment]
Ok I've actually removed all uses of `std`/`alloc` in the crate, so the extern crate thing isn't necessary anymore. Regarding feature flags, are you sure it's necessary? Currently the only that needs std is `tests/kat.rs`. Can we just omit features entirely and say that KAT needs std?

**Comment by pinkforest** [comment]
Cool ok - it's just standard feature flags but no worries makes sense - However if you have any Errors and you would like to support MSRV < 1.80 (not yet released) then I suggest using std feature to allow error gating to std's Error if you have fallible implementations - I left another issue for unwrap() as I wasn't sure what was the intent with panic over errors

**Comment by rozbb** [comment]
Thank you!

**Comment by rozbb** [comment]
Ugh it's complaining about something


https://github.com/rozbb/saber-rs/actions/runs/9634880583/workflow

**Comment by pinkforest** [comment]
Extra linefeed there, the yaml is pits

**Pull request merged**
